from .campus import *
from .degree import *
from .discipline import *
from .group import *
from .institute import *
from .lesson import *
from .lesson_call import *
from .lesson_type import *
from .msg import Msg
from .period import *
from .room import *
from .teacher import *
