version: "3.9"

services:
  proxy:
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.services.traefik-traefik-public.loadbalancer.server.port=80

  pgadmin:
    ports:
      - "5050:5050"

  backend:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
      - traefik.http.services.traefik-backend.loadbalancer.server.port=8080