version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - app-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - default
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  frontend:
#    image: ${FRONTEND_IMAGE}
##    build:
##      context: .
##      dockerfile: ./public/Dockerfile
#    networks:
#      - proxy
#      - default
#    environment:
#        VIRTUAL_PATH: "/"
#        VIRTUAL_HOST: ${DOMAIN}
#        LETSENCRYPT_HOST: ${DOMAIN}
#        VIRTUAL_PORT: '3000'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    volumes:
      - .:/app
      - ./docs:/app/app/parser/docs # schedule docs
    networks:
      - default
    environment:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        DB_HOST: ${DB_HOST}

  broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASS}
    volumes:
      - broker:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics check_running
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
        BROKER_URL: ${BROKER_URL}
        LOG_LEVEL: DEBUG
        C_FORCE_ROOT: true
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - default


volumes:
  app-db-data:
  broker:
