"""First revision

Revision ID: 0d908209ac89
Revises: 
Create Date: 2023-05-28 20:52:16.457899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d908209ac89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_campus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_campus_name'), 'schedule_campus', ['name'], unique=True)
    op.create_index(op.f('ix_schedule_campus_short_name'), 'schedule_campus', ['short_name'], unique=True)
    op.create_table('schedule_degree',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_degree_name'), 'schedule_degree', ['name'], unique=True)
    op.create_table('schedule_discipline',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_discipline_name'), 'schedule_discipline', ['name'], unique=True)
    op.create_table('schedule_institute',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_institute_name'), 'schedule_institute', ['name'], unique=True)
    op.create_index(op.f('ix_schedule_institute_short_name'), 'schedule_institute', ['short_name'], unique=True)
    op.create_table('schedule_lesson_call',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_lesson_call_num'), 'schedule_lesson_call', ['num'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_call_time_end'), 'schedule_lesson_call', ['time_end'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_call_time_start'), 'schedule_lesson_call', ['time_start'], unique=False)
    op.create_table('schedule_lesson_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_lesson_type_name'), 'schedule_lesson_type', ['name'], unique=True)
    op.create_table('schedule_period',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_teacher',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_teacher_name'), 'schedule_teacher', ['name'], unique=True)
    op.create_table('schedule_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('institute_id', sa.BigInteger(), nullable=False),
    sa.Column('degree_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['schedule_degree.id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['schedule_institute.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['schedule_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_group_degree_id'), 'schedule_group', ['degree_id'], unique=False)
    op.create_index(op.f('ix_schedule_group_institute_id'), 'schedule_group', ['institute_id'], unique=False)
    op.create_index(op.f('ix_schedule_group_name'), 'schedule_group', ['name'], unique=False)
    op.create_index(op.f('ix_schedule_group_period_id'), 'schedule_group', ['period_id'], unique=False)
    op.create_table('schedule_room',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['schedule_campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_room_name'), 'schedule_room', ['name'], unique=False)
    op.create_table('schedule_lesson',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('call_id', sa.BigInteger(), nullable=False),
    sa.Column('discipline_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('lesson_type_id', sa.BigInteger(), nullable=True),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('weeks', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['schedule_lesson_call.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['schedule_discipline.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['schedule_group.id'], ),
    sa.ForeignKeyConstraint(['lesson_type_id'], ['schedule_lesson_type.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['schedule_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_lesson_call_id'), 'schedule_lesson', ['call_id'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_discipline_id'), 'schedule_lesson', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_group_id'), 'schedule_lesson', ['group_id'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_lesson_type_id'), 'schedule_lesson', ['lesson_type_id'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_room_id'), 'schedule_lesson', ['room_id'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_weekday'), 'schedule_lesson', ['weekday'], unique=False)
    op.create_index(op.f('ix_schedule_lesson_weeks'), 'schedule_lesson', ['weeks'], unique=False)
    op.create_table('schedule_lessons_to_teachers',
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['schedule_lesson.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['schedule_teacher.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'teacher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_lessons_to_teachers')
    op.drop_index(op.f('ix_schedule_lesson_weeks'), table_name='schedule_lesson')
    op.drop_index(op.f('ix_schedule_lesson_weekday'), table_name='schedule_lesson')
    op.drop_index(op.f('ix_schedule_lesson_room_id'), table_name='schedule_lesson')
    op.drop_index(op.f('ix_schedule_lesson_lesson_type_id'), table_name='schedule_lesson')
    op.drop_index(op.f('ix_schedule_lesson_group_id'), table_name='schedule_lesson')
    op.drop_index(op.f('ix_schedule_lesson_discipline_id'), table_name='schedule_lesson')
    op.drop_index(op.f('ix_schedule_lesson_call_id'), table_name='schedule_lesson')
    op.drop_table('schedule_lesson')
    op.drop_index(op.f('ix_schedule_room_name'), table_name='schedule_room')
    op.drop_table('schedule_room')
    op.drop_index(op.f('ix_schedule_group_period_id'), table_name='schedule_group')
    op.drop_index(op.f('ix_schedule_group_name'), table_name='schedule_group')
    op.drop_index(op.f('ix_schedule_group_institute_id'), table_name='schedule_group')
    op.drop_index(op.f('ix_schedule_group_degree_id'), table_name='schedule_group')
    op.drop_table('schedule_group')
    op.drop_index(op.f('ix_schedule_teacher_name'), table_name='schedule_teacher')
    op.drop_table('schedule_teacher')
    op.drop_table('schedule_period')
    op.drop_index(op.f('ix_schedule_lesson_type_name'), table_name='schedule_lesson_type')
    op.drop_table('schedule_lesson_type')
    op.drop_index(op.f('ix_schedule_lesson_call_time_start'), table_name='schedule_lesson_call')
    op.drop_index(op.f('ix_schedule_lesson_call_time_end'), table_name='schedule_lesson_call')
    op.drop_index(op.f('ix_schedule_lesson_call_num'), table_name='schedule_lesson_call')
    op.drop_table('schedule_lesson_call')
    op.drop_index(op.f('ix_schedule_institute_short_name'), table_name='schedule_institute')
    op.drop_index(op.f('ix_schedule_institute_name'), table_name='schedule_institute')
    op.drop_table('schedule_institute')
    op.drop_index(op.f('ix_schedule_discipline_name'), table_name='schedule_discipline')
    op.drop_table('schedule_discipline')
    op.drop_index(op.f('ix_schedule_degree_name'), table_name='schedule_degree')
    op.drop_table('schedule_degree')
    op.drop_index(op.f('ix_schedule_campus_short_name'), table_name='schedule_campus')
    op.drop_index(op.f('ix_schedule_campus_name'), table_name='schedule_campus')
    op.drop_table('schedule_campus')
    # ### end Alembic commands ###
