"""default value for max_week

Revision ID: 45bb8c7682d2
Revises: f3638a25d218
Create Date: 2023-08-19 13:55:35.542370

"""
from alembic import op
import sqlalchemy as sa

from app.database.tables import Settings

# revision identifiers, used by Alembic.
revision = '45bb8c7682d2'
down_revision = 'f3638a25d218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    settings = Settings(max_week=17)
    session.add(settings)
    session.commit()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
