"""First revision

Revision ID: 786b5777f282
Revises: 
Create Date: 2022-10-21 21:06:39.663447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '786b5777f282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_campus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_degree',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_discipline',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_institute',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('short_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_lesson_call',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_lesson_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_period',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_teacher',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=True),
    sa.Column('degree_id', sa.BigInteger(), nullable=True),
    sa.Column('institute_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['schedule_degree.id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['schedule_institute.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['schedule_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_room',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['schedule_campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_lesson',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('call_id', sa.BigInteger(), nullable=False),
    sa.Column('discipline_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('lesson_type_id', sa.BigInteger(), nullable=True),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('weeks', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['schedule_lesson_call.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['schedule_discipline.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['schedule_group.id'], ),
    sa.ForeignKeyConstraint(['lesson_type_id'], ['schedule_lesson_type.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['schedule_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_lessons_to_teachers',
    sa.Column('lesson_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['schedule_lesson.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['schedule_teacher.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_lessons_to_teachers')
    op.drop_table('schedule_lesson')
    op.drop_table('schedule_room')
    op.drop_table('schedule_group')
    op.drop_table('schedule_teacher')
    op.drop_table('schedule_period')
    op.drop_table('schedule_lesson_type')
    op.drop_table('schedule_lesson_call')
    op.drop_table('schedule_institute')
    op.drop_table('schedule_discipline')
    op.drop_table('schedule_degree')
    op.drop_table('schedule_campus')
    # ### end Alembic commands ###
