"""add settings table

Revision ID: f3638a25d218
Revises: 0d908209ac89
Create Date: 2023-08-19 10:51:26.691126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3638a25d218'
down_revision = '0d908209ac89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('max_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_settings_id'), 'schedule_settings', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_settings_max_week'), 'schedule_settings', ['max_week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_settings_max_week'), table_name='schedule_settings')
    op.drop_index(op.f('ix_schedule_settings_id'), table_name='schedule_settings')
    op.drop_table('schedule_settings')
    # ### end Alembic commands ###
