from app.services.api.campus import CampusService
from app.services.api.degree import DegreeService
from app.services.api.discipline import DisciplineService
from app.services.api.group import GroupService
from app.services.api.institute import InstituteService
from app.services.api.lesson import LessonService
from app.services.api.lesson_call import LessonCallService
from app.services.api.lesson_type import LessonTypeService
from app.services.api.period import PeriodService
from app.services.api.room import RoomService
from app.services.api.teacher import TeacherService
