from app.services.db.campus import CampusDBService
from app.services.db.degree import DegreeDBService
from app.services.db.discipline import DisciplineDBService
from app.services.db.group import GroupDBService
from app.services.db.institute import InstituteDBService
from app.services.db.lesson import LessonDBService
from app.services.db.lesson_call import LessonCallDBService
from app.services.db.lesson_type import LessonTypeDBService
from app.services.db.period import PeriodDBService
from app.services.db.room import RoomDBService
from app.services.db.teacher import TeacherDBService
