from app.models.campus import *
from app.models.degree import *
from app.models.discipline import *
from app.models.group import *
from app.models.institute import *
from app.models.lesson import *
from app.models.lesson_call import *
from app.models.lesson_type import *
from app.models.lks_schedule import *
from app.models.msg import *
from app.models.period import *
from app.models.room import *
from app.models.settings import *
from app.models.teacher import *
from app.models.utils import *
from app.models.version import *
