name: Check and Test

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check codestyle
        run: |
          flake8 --config .flake8 app tests worker
          black --config pyproject.toml --diff --check app tests worker
          isort --check-only app tests worker
#  test:
#    runs-on: ubuntu-latest
#    needs: [check]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Setup Python 3.9
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.9'
#          cache: 'pip'
#      - name: Install dependencies
#        run: pip install -r requirements.txt
#      - name: Test backend
#        run: |
#          python -m pytest --asyncio-mode=strict -v
