#name: Check and Test
#
#on:
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  check-backend:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install poetry
#        run: pipx install poetry
#      - name: Setup Python 3.9
#        uses: actions/setup-python@v4
#        id: poetry-cache
#        with:
#          python-version: '3.9'
#          cache: 'poetry'
#      - if: steps.poetry-cache.outputs.cache-hit != 'true'
#        name: Install dependencies
#        run: poetry install
#      - name: Check codestyle
#        run: |
#          poetry run flake8 app tests
#          poetry run black --diff --check app tests
#          poetry run isort --check-only app tests
#  test-backend:
#    runs-on: ubuntu-latest
#    needs: [check-backend]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install poetry
#        run: pipx install poetry
#      - name: Setup Python 3.9
#        uses: actions/setup-python@v4
#        id: poetry-cache
#        with:
#          python-version: '3.9'
#          cache: 'poetry'
#      - if: steps.poetry-cache.outputs.cache-hit != 'true'
#        name: Install dependencies
#        run: poetry install
#      - name: Test backend
#        run: poetry run pytest --asyncio-mode=strict -v
