on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Workflow password'
        type: string
        required: true

jobs:
  clear-prod-broker:
    runs-on: mn-rtu-gh-runner
    steps:
      - env:
          PASSWORD: ${{ inputs.password }}
      - name: Check workflow password(true)
        if: $PASSWORD == ${{ secrets.DB_CLEAR_PASSWORD }}
        run: |
            docker volume rm broker || true
            docker volume create broker
      - name: Check workflow password(false)
        if: $PASSWORD != ${{ secrets.DB_CLEAR_PASSWORD }}
        run: |
            echo "Incorrect action password"
            