#name: Clear production broker
#
#on:
#  workflow_dispatch:
#    inputs:
#      password:
#        description: 'Workflow password'
#        type: string
#        required: true
#
#env:
#  PASSWORD: ${{ inputs.password }}
#  DB_CLEAR_PASSWORD: ${{ secrets.DB_CLEAR_PASSWORD }}
#
#jobs:
#  clear-prod-broker:
#    runs-on: mn-rtu-timetable-runner
#    steps:
#      - name: Clear production broker
#        run: |
#            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
#              docker volume rm broker --force
#              docker volume create broker
#            else
#              echo "Incorrect action password"
#            fi
