name: Prepair VM

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Workflow password'
        type: string
        required: true

env:
  PASSWORD: ${{ inputs.password }}
  DB_CLEAR_PASSWORD: ${{ secrets.DB_CLEAR_PASSWORD }}

jobs:
  down-timetable:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Down service
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.PRODUCTION_FOLDER }}
              docker compose down
            else
              echo "Incorrect action password"
            fi
  down-promtail:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Down promtail agent
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.CORE_FOLDER }}
              docker container rm -f promtail-logger
            else
              echo "Incorrect action password"
            fi
  clear-vm:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Clear VM
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.CORE_FOLDER }}
              docker image prune -af
              docker volume prune -f
              docker system prune -f
              docker network create proxy
            else
              echo "Incorrect action password"
            fi
  create-proxy-network:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Create proxy
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.CORE_FOLDER }}
              docker network create proxy
            else
              echo "Incorrect action password"
            fi
  copy-new-config:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Copy new configurations
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.PRODUCTION_FOLDER }}
              curl -O https://gist.githubusercontent.com/Dragonprod/36e43350021cc0e696e01a37b83139d8/raw/6d24fbe75af81e44062c1cbf1f82e9d26813f946/.env
              curl -O https://gist.githubusercontent.com/Dragonprod/6e7e68474110ae05d3e343515a5dd8a6/raw/72708f70b12341e3fc782a5a01bc8e3f5a6a1ff8/docker-compose.yml
            else
              echo "Incorrect action password"
            fi
  deploy-promtail:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Deploy promtail
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.CORE_FOLDER }}
              docker run -d --name=promtail-logger -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/promtail/config.yml:/etc/promtail/config.yml:z grafana/promtail:latest
            else
              echo "Incorrect action password"
            fi
  deploy-service:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Deploy service
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.PRODUCTION_FOLDER }}
              docker compose pull
              docker compose up -d --build
            else
              echo "Incorrect action password"
            fi
  
