name: Clear production database

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Workflow password'
        type: string
        required: true

env:
  PASSWORD: ${{ inputs.password }}
  DB_CLEAR_PASSWORD: ${{ secrets.DB_CLEAR_PASSWORD }}

jobs:
  logs:
    runs-on: mn-rtu-timetable-runner
    steps:
      - name: Logs
        run: |
            if [[ $PASSWORD == $DB_CLEAR_PASSWORD ]]; then
              cd ${{ secrets.PRODUCTION_FOLDER }}
              docker logs --follow rtu-mirea-timetable-backend-1
            else
              echo "Incorrect action password"
            fi
