on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Workflow password'
        type: string
        required: true

jobs:
  migrate-prod-db:
    runs-on: mn-rtu-gh-runner
    steps:
      - env:
          PASSWORD: ${{ inputs.password }}
      - name: Check workflow password(true)
        if: $PASSWORD == ${{ secrets.DB_CLEAR_PASSWORD }}
        run: |
            cd ${{ secrets.PRODUCTION_FOLDER }}
            docker compose exec backend alembic upgrade head
      - name: Check workflow password(false)
        if: $PASSWORD != ${{ secrets.DB_CLEAR_PASSWORD }}
        run: |
            echo "Incorrect action password"
            